### ISSUE TITLE
generate_apps_plan.py doesn't works

### ISSUE THREAD

**Issue by Yuki2L0ve** [sssszh/CodePLAN#1]
Congratulations on your work and I am very interested in your paper. I'm a newbie and I'm having some problems reproducing your code. I filled in my OpenAI key in generate_apps_plan.py and ran the command. But there isn't any output. As shown in the picture. Is this a problem with calling openai's gpt-3.5-turbo interface, or is there something wrong with my OpenAI key?
![image](https://github.com/sssszh/CodePLAN/assets/70561109/01d6d288-2df6-4c78-840d-c15e9430bb7e)

**Comment by sssszh** [comment]
Sorry, I found a problem with the data parameter path in the execute command. You can optionally change the execution command to: `python generate_apps_plan.py --test_path ... /data/apps/train --save_path ... /data/apps/train --start 0 --end 5000` or fill in these parameters in the executed code.

One more thing to remember is that I initially ran this code on Windows, if you want to run it on Linux, please note that '\*' is changed to '/*' in line 14 and '\\' is changed to '/' in line 31.

I hope this will solve your problem.

**Comment by sssszh** [comment]
> Congratulations on your work and I am very interested in your paper. I'm a newbie and I'm having some problems reproducing your code. I filled in my OpenAI key in generate_apps_plan.py and ran the command. But there isn't any output. As shown in the picture. Is this a problem with calling openai's gpt-3.5-turbo interface, or is there something wrong with my OpenAI key? ![image](https://private-user-images.githubusercontent.com/70561109/318201953-01d6d288-2df6-4c78-840d-c15e9430bb7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NzE3MTgsIm5iZiI6MTcxMTg3MTQxOCwicGF0aCI6Ii83MDU2MTEwOS8zMTgyMDE5NTMtMDFkNmQyODgtMmRmNi00Yzc4LTg0MGQtYzE1ZTk0MzBiYjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA3NTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMDA3ODhmNTUzZDIyZWU4YTZlNjkyMjdkNWQ0NmUyMGYzMDJlZDhlYTlkYzE5NTYxMzhmYjFhOGE3Y2I0ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rY0bk_caBLFpdICmkviHpvk3mjmgFIXIXkQpufaiP9k)

Sorry, I found a problem with the data parameter path in the execute command. You can optionally change the execution command to:
 `python generate_apps_plan.py --test_path ../data/apps/train --save_path ../data/apps/train --start 0 --end 5000` 
or fill in these parameters in the executed code.

One more thing to remember is that I initially ran this code on Windows, if you want to run it on Linux, please note that '\\\*' is changed to '/*' in line 14 and '\\\\' is changed to '/' in line 31.

I hope this will solve your problem.

**Comment by Yuki2L0ve** [comment]
> > Congratulations on your work and I am very interested in your paper. I'm a newbie and I'm having some problems reproducing your code. I filled in my OpenAI key in generate_apps_plan.py and ran the command. But there isn't any output. As shown in the picture. Is this a problem with calling openai's gpt-3.5-turbo interface, or is there something wrong with my OpenAI key? ![image](https://private-user-images.githubusercontent.com/70561109/318201953-01d6d288-2df6-4c78-840d-c15e9430bb7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NzE3MTgsIm5iZiI6MTcxMTg3MTQxOCwicGF0aCI6Ii83MDU2MTEwOS8zMTgyMDE5NTMtMDFkNmQyODgtMmRmNi00Yzc4LTg0MGQtYzE1ZTk0MzBiYjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA3NTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMDA3ODhmNTUzZDIyZWU4YTZlNjkyMjdkNWQ0NmUyMGYzMDJlZDhlYTlkYzE5NTYxMzhmYjFhOGE3Y2I0ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rY0bk_caBLFpdICmkviHpvk3mjmgFIXIXkQpufaiP9k)
> 
> Sorry, I found a problem with the data parameter path in the execute command. You can optionally change the execution command to: `python generate_apps_plan.py --test_path ../data/apps/train --save_path ../data/apps/train --start 0 --end 5000` or fill in these parameters in the executed code.
> 
> One more thing to remember is that I initially ran this code on Windows, if you want to run it on Linux, please note that '\*' is changed to '/*' in line 14 and '\\' is changed to '/' in line 31.
> 
> I hope this will solve your problem.

![%` Y7LJO0S59GAJRX@P)EPY](https://github.com/sssszh/CodePLAN/assets/70561109/1baa77b1-0ee0-45d7-ad32-d32b93c82f81)

Thank you very much for your response. I have solved the problem. However, I encountered an error when running the following line of code: 
`python train_codet5.py --model codet5-large-ntp-py --save_dir ./models -- train_path ./data/appps/train --tuning_mode plan --clone_pl_head True --epochs 10`
 The error is shown in the figure. I found that it seems `deepspeed_reinit` has been removed from `transformers.deepspeed`. Therefore, I would like to ask if you could provide some solutions. Thank you very much!

**Comment by sssszh** [comment]
@Yuki2L0ve Probably because of the transformer version, I overlooked this when I was organizing the code, you can remove `deepspeed_reinit`. The training process does not use deepspeed.

**Comment by Yuki2L0ve** [comment]
> @Yuki2L0ve Probably because of the transformer version, I overlooked this when I was organizing the code, you can remove `deepspeed_reinit`. The training process does not use deepspeed.

Thank you very much for your response. I have solved the problem. However, I encountered an error。
when running the following line of code:
`python train_codet5.py --model codet5-large-ntp-py --save_dir ./models -- train_path ./data/appps/train --tuning_mode plan --clone_pl_head True --epochs 10`

The error is shown in the figure.
![NJFZ $}I}K1NLP%RVQ7GA`7](https://github.com/sssszh/CodePLAN/assets/70561109/6a7d2700-3653-4176-b78f-6cfceab05352)
I've fixed.

Next when running the following line of code:
`python generate_codet5.py --test_path data/apps/test -- output_path ./outputs/codes --model_path ./model --plan_head True --is_plan False --temperature`

The error is shown in the figure.
![~M_6WXU9H%Z0PPRZNL {)1L](https://github.com/sssszh/CodePLAN/assets/70561109/3f5ce4d3-24ff-4e52-a943-bde7ffd9fd87)
I've fixed.

But when running the following line of code:
`python generate_codet5_plan.py --test_path ./data/apps/test --output_path ./outputs/plans --model_path ./model --plan_head True --is_plan True --temperature 0.6`

The error is shown in the figure.
![C5ANUYS4H6MDOHNN9FW5GAM](https://github.com/sssszh/CodePLAN/assets/70561109/cb95def2-5beb-4bb9-8ea3-d40bbe47f72d)

I guessed that `args.json` might be `config.json`, so I copied a copy of `args.json` and named it `config.json`. However, I still encountered an error.
The error is shown in the figure.
![image](https://github.com/sssszh/CodePLAN/assets/70561109/845912f6-2b35-4e1a-9540-847e0affa87b)

Could you please provide some solutions? Thank you very much.

**Comment by sssszh** [comment]
@Yuki2L0ve The problem is because you didn't successfully save the model weights while training the model. Note that the `save_freq` parameter means to save the model weights at intervals of how many steps, and since only a small amount of data was used and a total of 30 steps were used for training, the model weights were not saved. 

Trying to set `save_freq` to a smaller setting will successfully save the model weights. There will be a folder named `checkpoint-XXX` in the save path, loading `./model/checkpoint-XXX` will solve the problem.
